# Generated by Django 3.2.6 on 2023-07-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generator', '0002_remove_question_option1_remove_question_option2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default='dtfyghgycfrd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default='ftfyhgxjhn', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default='gyutgydtrhgy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(default='gytshuyuyd', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
